spring:
  profiles:
    active: local

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ucenter?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    initialization-mode: always

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
